### ISSUE TITLE
Creating a new user

### ISSUE THREAD

**Issue by Mensah22** [nsantiago2719/learning-management-system#1]
When creating a new user (Student) I get this error message:
**Mongoid::Errors::NoClientConfig - 
message:
  No configuration could be found for a client named 'default'.
summary:
  When attempting to create the new client, Mongoid could not find a client configuration for the name: 'default'. This is necessary in order to know the host, port, and options needed to connect.**

**Comment by nsantiago2719** [comment]
You'll need to configure your `database.yml` file. And also you'll need to install mongoDB.
