### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by Mensah22** [nsantiago2719/learning-management-system#2]
I'm not sure if this is on purpose, but the **config/secrets.yml.sample** breaks the app. I removed the .sample and it works. Am I supposed to remove it or is there another file?

**Comment by nsantiago2719** [comment]
@Mensah22 Yes you are suppose to remove the `.sample`. It is for the security of the app so that secret tokens won't be shared to anyone except you alone. You'll also need to remove the `.sample` of `config/database.yml.sample`.
