### ISSUE TITLE
Bootstrap restyle

### ISSUE THREAD

**Issue by coder2000** [nsantiago2719/learning-management-system#21]
I am working at restyling the site with bootstrap. We don't have to keep using it if you don't want. Here are a couple of screenshots to show what it looks like.
![localhost-3000-](https://user-images.githubusercontent.com/27944/29884835-51a8f740-8d7a-11e7-9c74-b12e9546224f.png)
![localhost-3000-new-instructor](https://user-images.githubusercontent.com/27944/29884834-51a6d69a-8d7a-11e7-854d-30e3488ca713.png)

**Comment by nsantiago2719** [comment]
Thanks this is very interesting, but I'm thinking on a custom theme in the feature where they can switch from semantic ui to bootstrap or to any theme they want. Anyways this is a good start for that. Great 👍
