### ISSUE TITLE
Mongodb vs Postgresql

### ISSUE THREAD

**Issue by coder2000** [nsantiago2719/learning-management-system#22]
I was just wondering the decision behind using Mongo over a more traditional db like Postgres.

**Comment by nsantiago2719** [comment]
Hi @coder2000, for having Mongo over other traditional db like postgres is about flexibility. In Relational Databases they are not really that  flexible unlike Document oriented nosqls like mongodb. Another thing to consider is the speed which where nosql databases excels. 3rd is for other feature that I'm planning on the platform like reporting, data analysis and much more, yes you can do it too on other databases but the features like mapreduce didn't exist on most of those databases. 4th, I don't see a complex transaction that is going to be in the platform where relational databases are great is.

**Comment by coder2000** [comment]
I agree with those points. One feature of relational dbs I like with ActiveRecord is the polymorphism. Right now I have a plan to rework the attachment system.

**Comment by coder2000** [comment]
I have found a way to do it with Mongodb
