### ISSUE TITLE
VideoJS x Turbolinks

### ISSUE THREAD

**Issue by nsantiago2719** [nsantiago2719/learning-management-system#7]
The video can't be played if you go another link then goes back to the video thru the browser back button. I'm thinking that this is caused of Turbolinks because it is not executing the script on if you click the back button.

**Comment by coder2000** [comment]
Where can you see videos? I haven't been able to get past the first screen when logged in as an instructor or student.

**Comment by nsantiago2719** [comment]
1. You need to create a repository first and add a video in that repository. 
2. Then create a group where you can post a topic.
3. Then create a topic/post you need to attach the video you uploaded earlier.

**Comment by coder2000** [comment]
I understand but an instructor cannot create a repository. Is there an admin user level?

**Comment by coder2000** [comment]
I was wrong. The Instructor user I created ended up being a student. I fixed the user creation form to set the proper role.

**Comment by nsantiago2719** [comment]
Thanks @coder2000 you are really a great help :) I'll be reviewing your PR now and will see if we can merge it today.
